---
- hosts: localhost
  connection: local
  vars:
    location: northeurope
    virtualnetwork: automationNetwork
    subnet: Servers
    tag_owner: arrow
    tag_project: ansibletraining

  vars_prompt:
    - name: adminUser
      prompt: "Type the name of your root/administrator account"
      private: no
    - name: adminPassword
      prompt: "Type the password of your root/administrator account"
      private: no

  tasks:
    - name: Azure Virtual Network
      include_role:
        name: jesperberth.az_virtualnetwork
      vars:
        resourcegroup: "ansible-{{ adminUser }}"
        virtualnetwork_name: "{{ virtualnetwork }}"
        cidr: 10.1.0.0/16
        subnet_name: "{{ subnet }}"
        subnet_cidr: 10.1.0.0/24
        owner: "{{ tag_owner }}"
        project: "{{ tag_project }}"

    - name: Azure Network Security Group
      include_role:
        name: jesperberth.az_securitygroup
      vars:
        resourcegroup: "ansible-{{ adminUser }}"
        networksecuritygroup_name: "{{ item.networksecuritygroup_name }}"
        rulename: "{{ item.rulename }}"
        ruleprotocol: "{{ item.ruleprotocol }}"
        rulesourceaddress: "{{ item.rulesourceaddress }}"
        ruledestinationportrange: "{{ item.ruledestinationportrange }}"
        ruleaccess: "{{ item.ruleaccess }}"
        rulepriority: "{{ item.rulepriority }}"
        ruledirection: "{{ item.ruledirection }}"
        owner: "{{ tag_owner }}"
        project: "{{ tag_project }}"
      loop:
        - {
            networksecuritygroup_name: "SG_Network",
            rulename: "AllowSSH",
            ruleprotocol: "Tcp",
            rulesourceaddress: "0.0.0.0/0",
            ruledestinationportrange: "22",
            ruleaccess: "Allow",
            rulepriority: "102",
            ruledirection: "Inbound",
          }
        - {
            networksecuritygroup_name: "SG_Network",
            rulename: "AllowRDP",
            ruleprotocol: "Tcp",
            rulesourceaddress: "0.0.0.0/0",
            ruledestinationportrange: "3389",
            ruleaccess: "Allow",
            rulepriority: "103",
            ruledirection: "Inbound",
          }
        - {
            networksecuritygroup_name: "SG_Network",
            rulename: "AllowHTTP",
            ruleprotocol: "Tcp",
            rulesourceaddress: "0.0.0.0/0",
            ruledestinationportrange: "80",
            ruleaccess: "Allow",
            rulepriority: "104",
            ruledirection: "Inbound",
          }
        - {
            networksecuritygroup_name: "SG_Network",
            rulename: "AllowHTTPS",
            ruleprotocol: "Tcp",
            rulesourceaddress: "0.0.0.0/0",
            ruledestinationportrange: "443",
            ruleaccess: "Allow",
            rulepriority: "105",
            ruledirection: "Inbound",
          }

    - name: Create network interfaces
      azure_rm_networkinterface:
        name: "{{ item }}_nic01"
        resource_group: "ansible-{{ adminUser }}"
        virtual_network: "{{ virtualnetwork }}"
        subnet_name: "{{ subnet }}"
        security_group: "SG_Network"
        ip_configurations:
          - name: "{{ item }}_nic01_ipconfig"
            public_ip_address_name: "{{ item }}_public_ip"
            primary: True
        tags:
          owner: "{{ tag_owner }}"
          project: "{{ tag_project }}"
      loop:
        - ansible
      async: 1000
      poll: 0
      register: create_nic

    - name: Wait for Network Interfaces
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 5
      with_items: "{{ create_nic.results }}"

    # Create Virtual Machines
    - name: Create Virtual Machines
      azure_rm_virtualmachine:
        resource_group: "ansible-{{ adminUser }}"
        name: "{{ item.name }}"
        os_type: "{{ item.os_type }}"
        admin_username: "{{ adminUser }}"
        admin_password: "{{ adminPassword }}"
        managed_disk_type: Standard_LRS
        state: present
        image:
          offer: "{{ item.offer }}"
          publisher: "{{ item.publisher }}"
          sku: "{{ item.sku }}"
          version: "{{ item.version }}"
        vm_size: "{{ item.size }}"
        network_interfaces: "{{ item.name }}_nic01"
        tags:
          owner: "{{ adminUser }}"
          delete: ansibletraining
      loop:
        - {
            "name": "ansible",
            "size": "Standard_A2_v2",
            "os_type": "Linux",
            "offer": "UbuntuServer",
            "publisher": "Canonical",
            "sku": "18.04-LTS",
            "version": "latest",
          }
      async: 1000
      poll: 0
      register: create_vm

    - name: Wait for Virtual Machines
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 5
      with_items: "{{ create_vm.results }}"

    #    - name: Add Datadisk to ansible VM
    #      azure_rm_manageddisk:
    #        name: datadisk
    #        location: "{{ location }}"
    #        resource_group: "ansible-{{ adminUser }}"
    #        disk_size_gb: 32
    #        managed_by: ansible

    - name: Create Azure VM extension to enable ansible
      azure_rm_virtualmachineextension:
        name: install-ansible
        resource_group: "ansible-{{ adminUser }}"
        virtual_machine_name: ansible
        publisher: Microsoft.Azure.Extensions
        virtual_machine_extension_type: CustomScript
        type_handler_version: "2.1"
        settings: '{"commandToExecute": "apt install ansible", "skipDos2Unix": true}'
        auto_upgrade_minor_version: true

    - name: Create an azure container registry
      azure_rm_containerregistry:
        name: "containerreg{{ adminUser }}"
        location: "{{ location }}"
        resource_group: "ansible-{{ adminUser }}"
        admin_user_enabled: true
        sku: Basic
