---
- hosts: tag_type_devops
  connection: local
  become: yes
  vars_prompt:
    - name: username
      prompt: Username
      private: no

    - name: account
      prompt: DevOps Account
      private: no

    - name: token
      prompt: Access Token
      private: no

    - name: pool
      prompt: Agent Pool
      private: no

  vars:
    ansible_python_interpreter: "auto"
    ansible_user: "{{ username }}"

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Allow User to run docker
      ansible.builtin.user:
        name: "{{ user }}"
        group: docker

    - name: Create Folder DevOpsAgent
      ansible.builtin.file:
        path: ~/DevOpsAgent
        state: directory

    - name: Download vsts-agent
      ansible.builtin.get_url:
        url: https://vstsagentpackage.azureedge.net/agent/2.190.0/vsts-agent-linux-x64-2.190.0.tar.gz
        dest: ~/DevOpsAgent/vsts-agent-linux-x64-2.190.0.tar.gz

    - name: Extract DevOpsAgent
      ansible.builtin.unarchive:
        src: ~/DevOpsAgent/vsts-agent-linux-x64-2.190.0.tar.gz
        dest: ~/DevOpsAgent

    - name: Configure DevOpsAgent
      shell: |
        ~/DevOpsAgent/config.sh --unattended --url https://dev.azure.com/{{ account }} --auth pat --token {{ token }} --pool {{ pool }}  --acceptTeeEula

# ./config.sh --unattended --url https://myaccount.visualstudio.com --auth pat --token myToken --pool default  --acceptTeeEula

# sudo pip install ansible[azure]
#
